[package]
name = "rust-juce-dsp"
version = "0.1.0"
authors = ["Subnite <subnite.mp3@gmail.com>"]
edition = "2024"
build = "build.rs"

[lib]
crate-type = [ "staticlib" ]

[build-dependencies]
cbindgen = "0.29"

[dependencies]
